### ISSUE TITLE
Refactor Procfile handling to use go-procfile-util

### ISSUE THREAD

**Issue by josegonzalez** [dokku/dokku#3196]
### High-level plan

- [x] Add a `check` subcommand to `go-procfile-util`. This can be used to validate the file.
- [x] Package `go-procfile-util` for release via deb and rpm.
- [x] Validate any existing procfile in the `ps::pre-deploy` or a new `pre-receive-app` hook. #2991
- [x] When extracting commands, ensure we expand the command using the environment for that given command. This will need to take the `PORT` into account, as that can change from web process to web process. Do this in the `scheduler-docker-local` plugin. #2793
- [x] When scaling processes, verify that the process type actually exists before performing actions. #2582

### Original Post

Our Procfile handling leaves something to be desired:

- It's not possible to validate if a Procfile is valid/invalid. This makes it easy for a developer to screw up the formatting and bork their deploy.
- For dockerfile deploys, Procfiles do not have their commands expanded. This causes issues with actually running those commands, as they are handed off to `docker run` as is.
- Process scaling doesn't actually check if the process exists.

Refactoring this to use an external tool that handles procfiles correctly would improve our own handling and hand off responsibility to a generic utility other projects can use.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
