### ISSUE TITLE
Roadmap for 0.2.0 Release

### ISSUE THREAD

**Issue by progrium** [dokku/dokku#55]
In no particular order:
- [x] Uses latest version of Docker again
- [x] Expose commands over SSH using sshcommand
- [x] App config / environment variable management
- [x] Basic hooks/plugin system
- [x] Pull nginx vhosts out into plugin
- [x] Separate dokku and buildstep more cleanly
- [x] Integration test coverage
- [x] export/import (ssh keys / acl + app configuration)
- [x] app delete command
- [x] Use dokku as the system user instead of git
- [x] run command
