### ISSUE TITLE
Ref #6056: Dokku not installable on Bookworm

### ISSUE THREAD

**Issue by Coffee2CodeNL** [dokku/dokku#6077]
##  Tasks

- [x] [dokku/docker-container-healthchecker](https://github.com/dokku/docker-container-healthchecker)
- [x] [dokku/docker-image-labeler](https://github.com/dokku/docker-image-labeler): Double CI, making a new patch
- [x] [dokku/docker-run-export](https://github.com/dokku/docker-run-export)
- [x] [dokku/dokku-event-listener](https://github.com/dokku/dokku-event-listener)
- [x] [dokku/dokku-update](https://github.com/dokku/dokku-update): Some issue with package_cloud returning 502
- [x] [dokku/lambda-builder](https://github.com/dokku/lambda-builder)
- [x] [dokku/netrc](https://github.com/dokku/netrc): Failed to build darwin files
- [x] [dokku/omakase](https://github.com/dokku/omakase)
- [x] [dokku/plugn](https://github.com/dokku/plugn)
- [x] [dokku/procfile-util](https://github.com/dokku/procfile-util)
- [x] [dokku/sshcommand](https://github.com/dokku/sshcommand): Some issue with package_cloud returning 502
- [x] [gliderlabs/herokuish](https://github.com/gliderlabs/herokuish)
- [x] [gliderlabs/sigil](https://github.com/gliderlabs/sigil): Some issue with package_cloud returning 502

### Description of problem

Dokku is not installable on bookworm (#6056):

```
The following packages have unmet dependencies:
 dokku : Depends: sshcommand (>= 0.12.0) but 0.7.0 is to be installed
         Depends: docker-image-labeler (>= 0.2.2) but it is not installable
         Depends: lambda-builder but it is not installable
         Depends: netrc but it is not installable
         Depends: procfile-util (>= 0.11.0) but it is not installable
         Recommends: herokuish (>= 0.3.4) but it is not installable
         Recommends: dokku-update but it is not installable
         Recommends: dokku-event-listener but it is not installable
E: Unable to correct problems, you have held broken packages.
```

### Steps to reproduce

-

### dokku report $APP_NAME

-

**Comment by josegonzalez** [comment]
Ah yeah, you added it to the bootstrap so now we use the bookworm repo instead of buster. That wasn't actually necessary, and since none of the other dependencies push to it, you now can't install it.

Fixes:

- Update all the other dependency repos (everything other than herokuish and sigil are in the dokku org, the others are in gliderlabs) to publish to bookworm.
- Use the bullseye repo (all our packages are exactly the same, we just publish to a new packagecloud repo for each).

As I'm currently busy with the 0.31 release, I'd happily accept patches for the former if you want to take a look at those :)

**Comment by Coffee2CodeNL** [comment]
Forkin' time!

**Comment by josegonzalez** [comment]
We'll also need gliderlabs/sigil and gliderlabs/herokuish.

Note that I won't have time to release these until later this week.

**Comment by Coffee2CodeNL** [comment]
That ought to be everything

**Comment by josegonzalez** [comment]
Just went through your PRs:

- We need to use tabs instead of spaces in Makefiles. Mind fixing that?
- Mind also removing `stretch` from the list of published packages? Thats EOL now.

**Comment by josegonzalez** [comment]
There are a few failures in uploads which I'm working through (seems to be related to packages that work for all architectures). Once those are done, this should work again.

**Comment by CodeZombieCH** [comment]
I have exactly the same problem on Debian 12. Unfortunately, I do not have the time to help contributing to resolve the issue.

A workaround is to use the version before the repository change:
[v0.30.9](https://github.com/dokku/dokku/releases/tag/v0.30.9)

(see https://github.com/dokku/dokku/pull/6056, changed
```
-deb https://packagecloud.io/dokku/dokku/debian/ bullseye main
+deb https://packagecloud.io/dokku/dokku/debian/ bookworm main
```

**Comment by josegonzalez** [comment]
The 502 issue was apparently me forgetting to update some repos to deal with a git change regarding safe directories...

**Comment by josegonzalez** [comment]
I'm now able to install dokku on bookworm! Closing this, thanks everyone for reporting the issue.
